### ISSUE TITLE
I don't see cheats after launch

### ISSUE THREAD

**Issue by AntonPiniaz** [holly-hacker/BulletForceHaxV2#23]
I'm running the project with `cargo run --bin server` , I also created the `config.toml` file and added `hax = true` there.
I get no errors at launch and the game launches at `http://localhost:48897`.
According to the logs, hax is activated: `Loaded config config="Config { config_file: \"config.toml\", port: 48897, game_dir: \"bfhax_data/game_files\", log_dir: \"bfhax_data/logs\", hax: true, hax_http: true }"`
But I don't see any menu or option to select/activate the cheat. Maybe some additional actions are needed or I'm missing something?

**Comment by holly-hacker** [comment]
If memory servers me right, there should be a link to `/hax` on the game's page. If not, you should be able to navigate to it yourself.

**Comment by AntonPiniaz** [comment]
There is no such router, but there is `/hax/ws`
When I go to it, I get the error `Connection header did not include 'upgrade'`
The problem seems to be somewhere in the `handle` function in `hax_ipc_server` or that this function does not receive `ws: WebSocketUpgrade`.
I haven't been in Rust long enough to figure out exactly what the problem is and fix it.

**Comment by holly-hacker** [comment]
Apologies, I checked the code and the game is hosted at `/game`, and the settings UI at `/`. I noticed you opened also #22 where you changed the inclusion path for the frontend files, which likely stems from a misunderstanding on how that works.

Before you can build the application, you must build the frontend project first. You can see the `Justfile` file for the commands that can do this.

**Comment by AntonPiniaz** [comment]
It works now, thank you!
But I didn't see anything that could be called a "cheat". Just lobby-related functions.
How about infinite UAV or aim or walking through walls/map?

**Comment by holly-hacker** [comment]
As mentioned in the README, there currently aren't any useful features at the moment. There is a minimap when you are in-game, but I don't know if that's on the main branch and it's not quite up-to-par yet either. Infinite UAV is certainly possible, walking through walls is not because this is merely a network proxy.

The actual implementation of these cheats requires a bunch of UI work and I don't find it very interesting, so I haven't gotten around to it yet. It shouldn't be very hard to implement once you familiarize yourself with the protocol and the project, though.
